services:
  backend:
    build:
      context: ../backend
    container_name: bcso_rh_backend
    restart: unless-stopped
    network_mode: host
    env_file:
      - ../backend/.env
    environment:
      DATABASE_URL: postgresql://bcso_db_user:20%^hXZe4YfgjU4DEz0k@127.0.0.1:5432/bcso_app?schema=public
      FRONTEND_URL: https://rh-bcso.nathanda95.fr
      DISCORD_REDIRECT_URI: https://rh-bcso-back.nathanda95.fr/auth/discord/callback
      PORT: 8090
    command: ["sh", "-c", "npx prisma migrate deploy && npm run dev"]

  frontend:
    build:
      context: ../frontend
    container_name: bcso_rh_frontend
    restart: unless-stopped
    ports:
      - "8091:80"
    depends_on:
      - backend
